package audit

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
	"unicode/utf8"
)

// skipHeaders are not emitted into .http files: hop-by-hop headers
// (RFC 7230 §6.1), values the HTTP client recomputes, and our own audit header.
var skipHeaders = map[string]bool{
	"Connection":          true,
	"Keep-Alive":          true,
	"Proxy-Connection":    true,
	"Proxy-Authorization": true,
	"Proxy-Authenticate":  true,
	"Te":                  true,
	"Trailer":             true,
	"Transfer-Encoding":   true,
	"Upgrade":             true,
	"Content-Length":      true,
	"Host":                true, // implied by the absolute-form request target
	"Accept-Encoding":     true, // let the replaying client negotiate (keeps responses readable)
	ActionHeader:          true,
}

// HTTPFileOptions controls .http rendering.
type HTTPFileOptions struct {
	// Actions supplies context comments for exchanges linked to DOM actions.
	Actions func(id string) (Action, bool)
}

// WriteHTTPFile renders exchanges in the .http format understood by
// kulala.nvim and VS Code REST Client:
//
//	### <title>
//	# @name <identifier>
//	METHOD absolute-URI HTTP/1.1
//	Header: value
//
//	body
//
// Each request is an RFC 7230 message (request-line, header fields, empty
// line, message body) and requests are separated by "###" lines.
func WriteHTTPFile(w io.Writer, exs []Exchange, opt HTTPFileOptions) error {
	bw := bufio.NewWriter(w)
	fmt.Fprintf(bw, "# Generated by web-cli — %d request(s)\n", len(exs))
	fmt.Fprintf(bw, "# Replay with kulala.nvim (<CR> / :lua require('kulala').run()) or VS Code REST Client (\"Send Request\").\n\n")
	for i, ex := range exs {
		if i > 0 {
			bw.WriteString("\n")
		}
		writeOne(bw, ex, opt)
	}
	return bw.Flush()
}

func writeOne(bw *bufio.Writer, ex Exchange, opt HTTPFileOptions) {
	title := fmt.Sprintf("#%d %s %s", ex.ID, ex.Method, ex.URL)
	fmt.Fprintf(bw, "### %s\n", oneLine(title))
	fmt.Fprintf(bw, "# @name req_%d\n", ex.ID)
	if ex.ActionID != "" {
		line := "# action: " + ex.ActionID
		if opt.Actions != nil {
			if a, ok := opt.Actions(ex.ActionID); ok {
				line += fmt.Sprintf(" %s hint=%d <%s> %q page=%s", a.Kind, a.Hint, a.Tag, a.Text, a.PageURL)
			}
		}
		bw.WriteString(oneLine(line) + "\n")
	}
	switch {
	case ex.Blocked:
		fmt.Fprintf(bw, "# response: %d (blocked by proxy rule)\n", ex.Status)
	case ex.Error != "":
		fmt.Fprintf(bw, "# response: error: %s\n", oneLine(ex.Error))
	case ex.Status != 0:
		fmt.Fprintf(bw, "# response: %d %s, %s, %d bytes\n", ex.Status, http.StatusText(ex.Status),
			orDash(ex.RespHeader.Get("Content-Type")), len(ex.RespBody))
	}
	for _, n := range ex.Intercepts {
		fmt.Fprintf(bw, "# intercept: %s\n", oneLine(n))
	}

	fmt.Fprintf(bw, "%s %s HTTP/1.1\n", ex.Method, ex.URL)
	keys := make([]string, 0, len(ex.ReqHeader))
	for k := range ex.ReqHeader {
		if !skipHeaders[http.CanonicalHeaderKey(k)] {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	for _, k := range keys {
		for _, v := range ex.ReqHeader[k] {
			fmt.Fprintf(bw, "%s: %s\n", k, oneLine(v))
		}
	}
	bw.WriteString("\n")

	if len(ex.ReqBody) > 0 {
		body := ex.ReqBody
		if dec, _, ok := Decompress(body, ex.ReqHeader.Get("Content-Encoding")); ok {
			body = dec
		}
		if utf8.Valid(body) {
			s := string(body)
			// A body line starting with "###" would be parsed as a separator.
			s = strings.ReplaceAll(s, "\n###", "\n ###")
			bw.WriteString(s)
			if !strings.HasSuffix(s, "\n") {
				bw.WriteString("\n")
			}
		} else {
			fmt.Fprintf(bw, "# (binary request body of %d bytes omitted)\n", len(body))
		}
		if ex.Truncated {
			bw.WriteString("# (body truncated by capture limit)\n")
		}
	}
}

func oneLine(s string) string {
	return strings.NewReplacer("\r", " ", "\n", " ").Replace(s)
}

func orDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}
